'use strict';
const $=selector=>document.querySelector(selector), C=MazeCore;
const worlds={
 forest:{icon:'🦊',goal:'🏡',name:'Zorrito',title:'Dibuja el camino hasta la casita',start:'Empieza en el círculo de Zorrito.',win:'¡Zorrito ya tiene un camino a casa!',wall:'#5b9366',paper:'#fffdf2',ink:'#c98b16'},
 sea:{icon:'🐠',goal:'🪸',name:'Burbujas',title:'Dibuja el camino hasta el coral',start:'Empieza en el círculo de Burbujas.',win:'¡Burbujas ya tiene un camino al coral!',wall:'#388c9f',paper:'#f0fcff',ink:'#b87815'},
 space:{icon:'🚀',goal:'🌕',name:'el cohete',title:'Dibuja el camino hasta la Luna',start:'Empieza en el círculo del cohete.',win:'¡Has dibujado un camino hasta la Luna!',wall:'#7d65a9',paper:'#fbf7ff',ink:'#bd7e1b'}
};
let prefs={level:0,world:'forest',assisted:true,autoHints:true,autoNext:true,fullscreen:true,sound:false,startPosition:'bottom',wallStyle:'hedge',missionMode:'none'};
try{const saved=JSON.parse(localStorage.getItem('laberintos-dibujo-v2')||'null');if(saved&&typeof saved==='object'){if(Number.isInteger(saved.level)&&C.levels[saved.level])prefs.level=saved.level;if(Object.hasOwn(worlds,saved.world))prefs.world=saved.world;if(['top','middle','bottom'].includes(saved.startPosition))prefs.startPosition=saved.startPosition;if(['hedge','brick'].includes(saved.wallStyle))prefs.wallStyle=saved.wallStyle;if(['none','two','three','ordered'].includes(saved.missionMode))prefs.missionMode=saved.missionMode;for(const key of ['assisted','autoHints','autoNext','fullscreen','sound'])if(typeof saved[key]==='boolean')prefs[key]=saved[key];}}catch{}
let screen='home',settingsOrigin='home',settingsDirty=false,maze=null,segments=[],ink=[],won=false,activePointer=null,pausedStroke=false,hintPoints=[],hintTimeout,autoHintTimeout,nextTimeout,confettiTimeout,frame=0,metrics=null,audioContext=null,holdTimer,holdFrame,holdStart,holdPointer=null,wallFeedbackStarted=0,wallFeedbackUntil=0,targets=[],pointerMode=null,panX=0,panY=0,panAnchor=null,recenterView=true;
const canvas=$('#maze'),ctx=canvas.getContext('2d');
const missionNames={none:'Solo llegar',two:'2 estrellas',three:'3 estrellas',ordered:'1, 2 y 3 en orden'};
for(let i=0;i<C.levels.length;i++){const level=C.levels[i],button=document.createElement('button');button.type='button';button.className='level'+(level.adult?' adult-level':'');button.dataset.level=String(i);button.setAttribute('aria-pressed','false');button.innerHTML=`<span class="level-number" aria-hidden="true">${level.adult?'A':i+1}</span><div><b>${level.icon} ${level.adult?'Adultos':`Nivel ${i+1}`} · ${level.label}</b><small>${level.cols} × ${level.rows} · ${level.difficulty}${i>=4?' · Desvíos largos':''}</small></div><span class="check" aria-hidden="true">✓</span>`;$('#level-list').append(button);}

function persist(){try{localStorage.setItem('laberintos-dibujo-v2',JSON.stringify(prefs));$('#settings-feedback').textContent='Los ajustes se guardan en este dispositivo.';}catch{$('#settings-feedback').textContent='Los ajustes se mantienen durante esta sesión.';}}
function updateControls(){document.body.dataset.world=prefs.world;document.querySelectorAll('.world').forEach(b=>{const selected=b.dataset.world===prefs.world;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});document.querySelectorAll('[data-level]').forEach(b=>{const selected=Number(b.dataset.level)===prefs.level;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});for(const [id,key] of [['assisted','assisted'],['auto-hints','autoHints'],['auto-next','autoNext'],['fullscreen','fullscreen'],['sound','sound']])$('#'+id).checked=prefs[key];$('#start-position').value=prefs.startPosition;$('#wall-style').value=prefs.wallStyle;$('#mission-mode').value=prefs.missionMode;const level=C.levels[prefs.level];$('#home-level').textContent=`${level.icon} ${level.adult?'Adultos':`Nivel ${prefs.level+1}`} · ${level.label}`;$('#home-mission').textContent=missionNames[prefs.missionMode]+' · Sin límite de tiempo';$('#game-level').textContent=level.adult?'Adultos · Reto maestro':`Nivel ${prefs.level+1} · ${level.difficulty}`;$('#game-title').textContent=worlds[prefs.world].title;$('#game-world-icon').textContent=worlds[prefs.world].icon;canvas.setAttribute('aria-label',`Laberinto de ${level.cols} columnas y ${level.rows} filas. Dibuja desde ${worlds[prefs.world].name} hasta el destino. También puedes dibujar con las flechas del teclado.`);}
function cancelTimers(){clearTimeout(autoHintTimeout);clearTimeout(hintTimeout);clearTimeout(nextTimeout);}
function endStroke(){const wasDrawing=activePointer!==null&&pointerMode==='draw';if(activePointer!==null){try{if(canvas.hasPointerCapture(activePointer))canvas.releasePointerCapture(activePointer);}catch{}}activePointer=null;pausedStroke=false;pointerMode=null;panAnchor=null;if(wasDrawing&&screen==='game'&&metrics)followInk();}
function setScreen(value){endStroke();cancelHold();cancelTimers();screen=value;document.body.dataset.screen=value;for(const name of ['home','settings','game'])$('#'+name+'-screen').hidden=name!==value;if(value==='game'){requestAnimationFrame(()=>{resizeCanvas();if(won)scheduleNext();else armAutoHint();});}else{try{screenOrientationUnlock();}catch{}if(value==='home')$('#play').focus({preventScroll:true});else $('#settings-back').focus({preventScroll:true});}}
function screenOrientationUnlock(){window.screen?.orientation?.unlock?.();}
function status(text){if($('#status').textContent!==text)$('#status').textContent=text;}
function generate(){cancelTimers();endStroke();maze=C.generate(prefs.level,Math.random,{startPosition:prefs.startPosition});wallFeedbackUntil=0;targets=C.missionTargets(maze,prefs.missionMode==='none'?0:prefs.missionMode==='two'?2:3).map((cell,index)=>({cell,index,collected:false}));recenterView=true;segments=C.walls(maze);ink=[C.center(maze.startCell,maze.cols)];won=false;hintPoints=[];$('#win-banner').hidden=true;$('#confetti').replaceChildren();clearTimeout(confettiTimeout);updateControls();updateMissionProgress();status(worlds[prefs.world].start+(targets.length?' Recoge las estrellas antes de llegar.':''));scheduleDraw();armAutoHint();}
function resetInk(){cancelTimers();endStroke();for(const target of targets)target.collected=false;updateMissionProgress();ink=[C.center(maze.startCell,maze.cols)];won=false;hintPoints=[];$('#win-banner').hidden=true;$('#confetti').replaceChildren();status('Vuelve a empezar en el círculo de salida.');followInk(true);scheduleDraw();armAutoHint();}
function exitFullscreen(){const exit=document.exitFullscreen||document.webkitExitFullscreen;if((document.fullscreenElement||document.webkitFullscreenElement)&&exit){try{Promise.resolve(exit.call(document)).catch(()=>{});}catch{}}}
function requestFullscreen(){if(!prefs.fullscreen||document.fullscreenElement||document.webkitFullscreenElement)return;const request=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(!request){$('#fullscreen-feedback').textContent='Este navegador no admite pantalla completa. El juego ocupa toda el área disponible.';return;}try{Promise.resolve(request.call(document.documentElement)).then(()=>{if(screen==='game'){try{Promise.resolve(window.screen?.orientation?.lock?.('landscape')).catch(()=>{});}catch{}}}).catch(()=>{$('#fullscreen-feedback').textContent='Si la barra del navegador sigue visible, puedes usar su opción de pantalla completa. En una PDI con ordenador: F11.';});}catch{$('#fullscreen-feedback').textContent='El juego ocupa toda el área disponible. En una PDI con ordenador puedes usar F11.';}}
function beginGame(){generate();setScreen('game');requestFullscreen();canvas.focus({preventScroll:true});}
function goHome(){closeAdult();setScreen('home');exitFullscreen();}
function openSettings(origin){settingsOrigin=origin;settingsDirty=false;closeAdult();setScreen('settings');updateControls();}
function finishSettings(){persist();updateControls();if(settingsOrigin==='game'){if(settingsDirty||!maze)generate();setScreen('game');canvas.focus({preventScroll:true});if(prefs.fullscreen)requestFullscreen();else exitFullscreen();}else setScreen('home');}
function setPan(x,y){if(!metrics)return;const stage=$('.maze-stage');panX=Math.max(0,Math.min(x,Math.max(0,metrics.width-stage.clientWidth)));panY=Math.max(0,Math.min(y,Math.max(0,metrics.height-stage.clientHeight)));canvas.style.transform=`translate(${-panX}px,${-panY}px)`;}
function canPan(){const stage=$('.maze-stage');return metrics&&(metrics.width>stage.clientWidth+1||metrics.height>stage.clientHeight+1);}
function followInk(force=false){if(!metrics||!ink.length)return;const stage=$('.maze-stage'),point=pixels(ink.at(-1)),margin=Math.min(90,stage.clientHeight*.2);let x=panX,y=panY;if(force){x=point.x-stage.clientWidth/2;y=point.y-stage.clientHeight/2;}else{if(point.x-x<margin)x=point.x-margin;if(point.x-x>stage.clientWidth-margin)x=point.x-stage.clientWidth+margin;if(point.y-y<margin)y=point.y-margin;if(point.y-y>stage.clientHeight-margin)y=point.y-stage.clientHeight+margin;}setPan(x,y);}
function resizeCanvas(){if(screen!=='game'||!maze)return;const stage=$('.maze-stage'),vw=stage.clientWidth,vh=stage.clientHeight;if(vw<1||vh<1)return;const minCell=52,padding=Math.max(14,Math.min(vw/maze.cols,vh/maze.rows)*.11),width=Math.max(vw,maze.cols*minCell+2*padding),height=Math.max(vh,maze.rows*minCell+2*padding),dpr=Math.min(window.devicePixelRatio||1,2);canvas.style.width=width+'px';canvas.style.height=height+'px';canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);metrics={width,height,dpr,padding,cw:(width-2*padding)/maze.cols,ch:(height-2*padding)/maze.rows};setPan(panX,panY);followInk(recenterView);recenterView=false;draw();}
function scheduleDraw(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;draw();});}
function pixels(point){return{x:metrics.padding+point.x*metrics.cw,y:metrics.padding+point.y*metrics.ch};}
function drawLine(points,color,width,dashed=false){if(points.length<2)return;ctx.beginPath();points.forEach((p,i)=>{const v=pixels(p);if(i)ctx.lineTo(v.x,v.y);else ctx.moveTo(v.x,v.y);});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash(dashed?[4,12]:[]);ctx.stroke();ctx.setLineDash([]);}
function disc(point,radius,color){const p=pixels(point);ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function wallDimensions(){const unit=metrics?Math.min(metrics.cw,metrics.ch):100;return {unit,wallWidth:Math.max(6,unit*.14),lineWidth:Math.max(5,unit*.072)};}
function collisionPadding(){const {unit,wallWidth,lineWidth}=wallDimensions();return Math.max(C.clearance,(wallWidth+lineWidth)/(2*unit)+.018);}
function touchesWall(point){const {unit,wallWidth}=wallDimensions();return C.blocked(point,point,segments,wallWidth/(2*unit)+.018);}
function flashWalls(){const now=performance.now();if(now<wallFeedbackUntil)return;wallFeedbackStarted=now;wallFeedbackUntil=now+720;status('¡Una pared! Vuelve al puntito y sigue por el camino.');scheduleDraw();}
function drawWalls(){
 const {unit,wallWidth}=wallDimensions(),now=performance.now();
 const red=now<wallFeedbackUntil&&(matchMedia('(prefers-reduced-motion: reduce)').matches||Math.floor((now-wallFeedbackStarted)/240)%2===0);
 const brick=prefs.wallStyle==='brick';
 const palettes={forest:['#315e3d','#538e48','#97bd70','#367449'],sea:['#25657a','#41969d','#88c6bb','#277889'],space:['#594570','#8672a3','#c2abd9','#6a5589']};
 const colors=red?['#9f3032','#dc5151','#ffb4a0','#b9393d']:brick?['#8c4f39','#cb805b','#f2d1ae','#a85f41']:palettes[prefs.world];
 ctx.beginPath();for(const wall of segments){const a=pixels({x:wall.x1,y:wall.y1}),b=pixels({x:wall.x2,y:wall.y2});ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);}
 ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=colors[0];ctx.lineWidth=wallWidth;ctx.stroke();ctx.strokeStyle=colors[1];ctx.lineWidth=wallWidth*.77;ctx.stroke();
 for(const wall of segments){
  const a=pixels({x:wall.x1,y:wall.y1}),b=pixels({x:wall.x2,y:wall.y2}),length=Math.hypot(b.x-a.x,b.y-a.y),angle=Math.atan2(b.y-a.y,b.x-a.x);
  ctx.save();ctx.translate(a.x,a.y);ctx.rotate(angle);
  if(brick){
   ctx.strokeStyle=colors[2];ctx.lineWidth=Math.max(1,wallWidth*.055);ctx.lineCap='butt';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(length,0);
   const block=Math.max(12,unit*.29);
   for(let x=block*.5;x<length;x+=block){ctx.moveTo(x,-wallWidth*.36);ctx.lineTo(x,0);}
   for(let x=block;x<length;x+=block){ctx.moveTo(x,0);ctx.lineTo(x,wallWidth*.36);}
   ctx.stroke();
  }else{
   const spacing=Math.max(5,wallWidth*.65);
   for(let j=0,x=spacing*.5;x<length;x+=spacing,j++){const side=j%2?1:-1;ctx.fillStyle=j%3?colors[2]:colors[3];ctx.beginPath();ctx.ellipse(x,side*wallWidth*.13,wallWidth*.23,wallWidth*.13,side*.55,0,Math.PI*2);ctx.fill();}
  }
  ctx.restore();
 }
}
function draw(){if(!maze||!metrics||screen!=='game')return;const {width,height,dpr,cw,ch}=metrics,w=worlds[prefs.world],unit=Math.min(cw,ch),lineWidth=wallDimensions().lineWidth,start=C.center(maze.startCell,maze.cols),goal=C.center(maze.goalCell,maze.cols),endpoint=ink.at(-1);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle=w.paper;ctx.fillRect(0,0,width,height);
 disc(goal,unit*.35,prefs.world==='forest'?'#e9f0d0':prefs.world==='sea'?'#d8f1f4':'#eae0f4');
 drawLine(ink,w.ink,lineWidth);drawLine(hintPoints,'#e1ad35',Math.max(5,unit*.055),true);
 drawWalls();drawTargets();
 disc(start,unit*.31,'#fffaf0');const at=pixels(start);ctx.beginPath();ctx.arc(at.x,at.y,unit*.33,0,Math.PI*2);ctx.strokeStyle='#dab045';ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.stroke();ctx.setLineDash([]);
 ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(20,Math.min(70,unit*.48))}px "Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif`;ctx.fillText(w.icon,at.x,at.y);const end=pixels(goal);ctx.fillText(w.goal,end.x,end.y);
 ctx.font=`bold ${Math.max(10,Math.min(14,unit*.12))}px "Trebuchet MS",Arial,sans-serif`;ctx.fillStyle='#66734c';ctx.fillText('SALIDA',at.x,at.y+unit*.35);ctx.fillText('LLEGADA',end.x,end.y+unit*.35);
 if(!won){disc(endpoint,Math.max(5,unit*.067),w.ink);const p=pixels(endpoint);ctx.beginPath();ctx.arc(p.x,p.y,unit*(pausedStroke?.22:.17),0,Math.PI*2);ctx.strokeStyle='#d9ac48';ctx.lineWidth=2;ctx.stroke();}
 if(performance.now()<wallFeedbackUntil)scheduleDraw();
}
function pointFromEvent(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left-metrics.padding)/metrics.cw,y:(event.clientY-r.top-metrics.padding)/metrics.ch};}
function canResume(point){return C.distance(point,ink.at(-1))<=C.levels[prefs.level].resumeRadius&&!C.blocked(ink.at(-1),point,segments,collisionPadding());}
function appendPoint(p){const last=ink.at(-1);if(C.distance(last,p)<.006)return;let match=-1,best=.038;for(let i=ink.length-5;i>=Math.max(0,ink.length-1500);i--){const distance=C.distance(ink[i],p);if(distance<best&&!C.blocked(last,ink[i],segments,collisionPadding())){match=i;best=distance;}}if(match>=0)ink.length=match+1;else ink.push(p);}
function updateMissionProgress(){const progress=$('#mission-progress');progress.hidden=!targets.length;progress.textContent=`★ ${targets.filter(t=>t.collected).length}/${targets.length}${prefs.missionMode==='ordered'?' · En orden':''}`;}
function collectAt(point){let message='';for(const target of targets){if(target.collected||C.distance(point,C.center(target.cell,maze.cols))>.27)continue;if(prefs.missionMode==='ordered'&&targets.find(t=>!t.collected)!==target){message=`Primero recoge la estrella ${targets.find(t=>!t.collected).index+1}.`;continue;}target.collected=true;updateMissionProgress();tone(790,.1);message=`¡Estrella recogida! ${targets.filter(t=>t.collected).length} de ${targets.length}.`;}return message;}
function drawTargets(){const unit=Math.min(metrics.cw,metrics.ch);for(const target of targets){const point=C.center(target.cell,maze.cols),p=pixels(point);if(target.collected){disc(point,unit*.15,'#e8ebd4');ctx.font=`bold ${Math.max(13,unit*.27)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#607d47';ctx.fillText('✓',p.x,p.y);continue;}disc(point,unit*.29,'#fff0b8');ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.min(46,unit*.51)}px sans-serif`;ctx.fillStyle='#d3941c';ctx.fillText('★',p.x,p.y);if(prefs.missionMode==='ordered'){ctx.font=`bold ${Math.max(12,unit*.18)}px Arial,sans-serif`;ctx.fillStyle='#473913';ctx.fillText(String(target.index+1),p.x,p.y+unit*.015);}}}
function paintToward(point){if(!maze||won)return false;if(touchesWall(point)){pausedStroke=true;flashWalls();return false;}if(C.cellAt(point,maze)<0)return false;const target=prefs.assisted?C.guide(point,maze):point,result=C.trace(ink.at(-1),target,segments,collisionPadding());let collectedMessage='';for(const p of result.points){appendPoint(p);collectedMessage=collectAt(p)||collectedMessage;}if(result.points.length){hintPoints=[];clearTimeout(hintTimeout);status(collectedMessage||'Si levantas el dedo, continúa en el puntito dorado.');armAutoHint();}if(result.blocked){pausedStroke=true;flashWalls();status('La línea se para en la pared. Vuelve al puntito y sigue por el camino.');}scheduleDraw();const goal=C.center(maze.goalCell,maze.cols);if(C.distance(ink.at(-1),goal)<.29){if(targets.every(t=>t.collected))complete();else status(`Antes de llegar, recoge ${targets.filter(t=>!t.collected).length} estrella${targets.filter(t=>!t.collected).length===1?'':'s'}.`);}return !result.blocked;}
function pointerDown(event){if(screen!=='game'||won||activePointer!==null||event.isPrimary===false||(event.pointerType==='mouse'&&event.button!==0))return;event.preventDefault();if(!metrics)resizeCanvas();const p=pointFromEvent(event),resume=canResume(p);if(touchesWall(p))flashWalls();if(!resume){if(canPan()){activePointer=event.pointerId;pointerMode='pan';panAnchor={x:event.clientX,y:event.clientY,panX,panY};canvas.setPointerCapture(event.pointerId);status('Desliza para mirar. Continúa dibujando desde el puntito dorado.');}else{status(ink.length===1?worlds[prefs.world].start:'Continúa en el puntito dorado, donde dejaste la línea.');scheduleDraw();}return;}activePointer=event.pointerId;pointerMode='draw';pausedStroke=false;canvas.setPointerCapture(event.pointerId);canvas.focus({preventScroll:true});paintToward(p);}
function pointerMove(event){if(activePointer!==event.pointerId||won)return;event.preventDefault();if(pointerMode==='pan'){setPan(panAnchor.panX+panAnchor.x-event.clientX,panAnchor.panY+panAnchor.y-event.clientY);return;}const samples=event.getCoalescedEvents?.(),events=samples?.length?samples:[event];for(const sample of events){const p=pointFromEvent(sample);if(touchesWall(p)){pausedStroke=true;flashWalls();continue;}if(C.cellAt(p,maze)<0){pausedStroke=true;continue;}if(pausedStroke){if(!canResume(p))continue;pausedStroke=false;}paintToward(p);if(won)break;}}
function armAutoHint(){clearTimeout(autoHintTimeout);if(screen!=='game'||won||!prefs.autoHints||$('#adult-dialog').open)return;autoHintTimeout=setTimeout(()=>{if(screen==='game'&&!won&&!$('#adult-dialog').open)showHint();},14000);}
function showHint(){if(!maze||won)return;clearTimeout(hintTimeout);clearTimeout(autoHintTimeout);const endpoint=ink.at(-1),i=C.cellAt(endpoint,maze),remaining=targets.filter(t=>!t.collected),dest=prefs.missionMode==='ordered'&&remaining.length?remaining[0].cell:remaining.length?remaining.reduce((best,t)=>C.path(maze.cells,maze.cols,maze.rows,i,t.cell).length<C.path(maze.cells,maze.cols,maze.rows,i,best.cell).length?t:best).cell:maze.goalCell,route=C.path(maze.cells,maze.cols,maze.rows,i,dest);hintPoints=[endpoint,...route.slice(0,3).map(i=>C.center(i,maze.cols))];status('Los puntitos dorados te ayudan a '+(remaining.length?'encontrar una estrella.':'llegar al destino.'));followInk();tone(620,.12);scheduleDraw();hintTimeout=setTimeout(()=>{hintPoints=[];scheduleDraw();armAutoHint();},6000);}
function tone(frequency,duration=.1,delay=0){if(!prefs.sound)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime+delay;osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(now);osc.stop(now+duration);}catch{}}
function complete(){won=true;endStroke();cancelTimers();hintPoints=[];$('#win-message').textContent=worlds[prefs.world].win;$('#win-banner').hidden=false;status('¡Has dibujado todo el camino!');[523,659,784,1047].forEach((f,i)=>tone(f,.22,i*.13));if(!matchMedia('(prefers-reduced-motion: reduce)').matches){for(let i=0;i<36;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.background=['#e6b956','#75a579','#e79271','#9bbacc'][i%4];p.style.animationDelay=Math.random()*.5+'s';$('#confetti').append(p);}confettiTimeout=setTimeout(()=>$('#confetti').replaceChildren(),3100);}scheduleDraw();scheduleNext();}
function scheduleNext(){clearTimeout(nextTimeout);if(won&&prefs.autoNext&&screen==='game'&&!$('#adult-dialog').open)nextTimeout=setTimeout(()=>{if(screen==='game'&&!$('#adult-dialog').open)generate();},3400);}
function keyboardDraw(d){if(won)return;const i=C.cellAt(ink.at(-1),maze),next=C.neighbor(i,d,maze.cols,maze.rows);if(next<0||maze.cells[i][d]){flashWalls();status('Hay una pared. Prueba otro camino.');return;}const middle=C.center(i,maze.cols);if(C.blocked(ink.at(-1),middle,segments,collisionPadding()))return;paintToward(middle);paintToward(C.center(next,maze.cols));followInk();}
function cancelHold(){clearTimeout(holdTimer);cancelAnimationFrame(holdFrame);holdPointer=null;$('#adult-menu').classList.remove('holding');$('#adult-menu').style.removeProperty('--hold-progress');}
function openAdult(){if(screen!=='game'||$('#adult-dialog').open)return;endStroke();cancelTimers();cancelHold();$('#hint').disabled=won;$('#adult-context').textContent=won?'¡Partida completada! Puedes elegir otra aventura.':'La partida se queda guardada mientras estás aquí.';$('#adult-dialog').showModal();$('#resume').focus();}
function closeAdult(){if($('#adult-dialog').open)$('#adult-dialog').close();}
function resume(){closeAdult();canvas.focus({preventScroll:true});armAutoHint();scheduleNext();}
$('#adult-menu').addEventListener('pointerdown',event=>{if(event.isPrimary===false||event.button>0)return;event.preventDefault();cancelHold();holdPointer=event.pointerId;$('#adult-menu').setPointerCapture(event.pointerId);holdStart=performance.now();$('#adult-menu').classList.add('holding');const animate=()=>{if(holdPointer===null)return;$('#adult-menu').style.setProperty('--hold-progress',Math.min(100,(performance.now()-holdStart)/12)+'%');holdFrame=requestAnimationFrame(animate);};holdFrame=requestAnimationFrame(animate);holdTimer=setTimeout(openAdult,1200);});
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#adult-menu').addEventListener(name,cancelHold);
$('#adult-menu').addEventListener('click',event=>{if(event.detail===0)openAdult();});
$('#adult-menu').addEventListener('contextmenu',event=>event.preventDefault());
$('#play').addEventListener('click',beginGame);$('#open-settings').addEventListener('click',()=>openSettings('home'));$('#settings-back').addEventListener('click',finishSettings);$('#settings-done').addEventListener('click',finishSettings);
document.querySelectorAll('.world').forEach(b=>b.addEventListener('click',()=>{prefs.world=b.dataset.world;updateControls();persist();}));
document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{prefs.level=Number(b.dataset.level);prefs.assisted=prefs.level<=1;prefs.autoHints=prefs.level<=1;settingsDirty=true;updateControls();persist();}));
for(const [id,key] of [['assisted','assisted'],['auto-hints','autoHints'],['auto-next','autoNext'],['fullscreen','fullscreen'],['sound','sound']])$('#'+id).addEventListener('change',event=>{prefs[key]=event.target.checked;persist();});
for(const [id,key] of [['start-position','startPosition'],['wall-style','wallStyle'],['mission-mode','missionMode']])$('#'+id).addEventListener('change',event=>{prefs[key]=event.target.value;if(key==='startPosition'||key==='missionMode')settingsDirty=true;persist();updateControls();});
$('#resume').addEventListener('click',resume);$('#close-adult').addEventListener('click',resume);$('#hint').addEventListener('click',()=>{resume();showHint();});$('#erase').addEventListener('click',()=>{closeAdult();resetInk();canvas.focus({preventScroll:true});});$('#new-maze').addEventListener('click',()=>{closeAdult();generate();canvas.focus({preventScroll:true});});$('#game-settings').addEventListener('click',()=>openSettings('game'));$('#go-home').addEventListener('click',goHome);
$('#adult-dialog').addEventListener('cancel',()=>{requestAnimationFrame(()=>{armAutoHint();scheduleNext();});});
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,event=>{if(event.pointerId===activePointer){endStroke();scheduleDraw();}});
document.addEventListener('keydown',event=>{if(screen!=='game'||$('#adult-dialog').open||event.altKey||event.ctrlKey||event.metaKey||event.target!==canvas)return;const directions={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3};if(Object.hasOwn(directions,event.key)){event.preventDefault();keyboardDraw(directions[event.key]);}else if(event.key==='Backspace'&&!won){event.preventDefault();ink.length=Math.max(1,ink.length-25);hintPoints=[];status('Puedes continuar desde el puntito dorado.');scheduleDraw();armAutoHint();}});
window.addEventListener('resize',resizeCanvas);document.addEventListener('fullscreenchange',()=>{endStroke();resizeCanvas();});
if(typeof ResizeObserver!=='undefined')new ResizeObserver(resizeCanvas).observe($('.maze-stage'));
document.addEventListener('visibilitychange',()=>{if(document.hidden){endStroke();cancelHold();cancelTimers();}else{armAutoHint();scheduleNext();}});
updateControls();
// Integración opcional: las acciones comparten el mismo estado que la interfaz.
if(document.modelContext?.registerTool){const lifetime=new AbortController();for(const tool of [
{name:'crear_laberinto',description:'Inicia un laberinto de dibujo. nivel: 0–7 para niveles infantiles 1–8; 8 para el reto de adultos. No solicita pantalla completa.',inputSchema:{type:'object',properties:{nivel:{type:'integer',minimum:0,maximum:8},aventura:{type:'string',enum:['forest','sea','space']}},additionalProperties:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['nivel','aventura'].includes(k)))throw new Error('Opciones inválidas');if(input.nivel!==undefined&&(!Number.isInteger(input.nivel)||!C.levels[input.nivel]))throw new Error('Nivel inválido');if(input.aventura!==undefined&&!Object.hasOwn(worlds,input.aventura))throw new Error('Aventura inválida');if(input.nivel!==undefined){prefs.level=input.nivel;prefs.assisted=prefs.level<=1;prefs.autoHints=prefs.level<=1;}if(input.aventura!==undefined)prefs.world=input.aventura;closeAdult();generate();setScreen('game');return {nivel:prefs.level,aventura:prefs.world,columnas:maze.cols,filas:maze.rows};}},
{name:'leer_partida_laberinto',description:'Consulta la aventura, el extremo del camino y si el laberinto se ha completado.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {pantalla:screen,nivel:prefs.level,aventura:prefs.world,extremo:ink.at(-1)||null,completado:won,estrellasRecogidas:targets.filter(t=>t.collected).length,estrellasTotales:targets.length};}}
]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false,...tool.annotations}},{signal:lifetime.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});}
